go install -v github.com/stamblerre/gocode@latest
go install -v github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
go install -v github.com/ramya-rao-a/go-outline@latest
go install -v github.com/acroca/go-symbols@latest
go install -v golang.org/x/tools/cmd/guru@latest
go install -v golang.org/x/tools/cmd/gorename@latest
go install -v github.com/cweill/gotests@latest
go install -v github.com/fatih/gomodifytags@latest
go install -v github.com/josharian/impl@latest
go install -v github.com/davidrjenni/reftools/cmd/fillstruct@latest
go install -v github.com/haya14busa/goplay/cmd/goplay@latest
go install -v github.com/godoctor/godoctor@latest
go install -v github.com/go-delve/delve/cmd/dlv@latest
go install -v github.com/stamblerre/gocode@latest
go install -v github.com/rogpeppe/godef@latest
go install -v github.com/sqs/goreturns@latest
go install -v golang.org/x/lint/golint@latest
go install -v golang.org/x/tools/gopls@latest